### ISSUE TITLE
Perform basic task analysis, deliver results as product backlog with user stories

### ISSUE THREAD

**Issue by zfrgt** [PavelLev/CourseManagementSystem#1]
User stories should begin with 'as <role> i want to <action description>, so i can <business value description>'. Desired amount is 10..15.
**Proposed template:** https://www.mountaingoatsoftware.com/agile/scrum/sprint-backlog
**Desired format:** either XLS/XLSX or PDF

**Comment by vasyaxparfenov** [comment]
This is our user stories.
[backlog.xlsx](https://github.com/PavelLev/CourseManagementSystem/files/508499/backlog.xlsx)

**Comment by zfrgt** [comment]
Thanks! See my notes on this below.
1. As a student I want to subscribe and unsubscribe for a course so that I can choose what to learn
   Business value is unclear here (un\subscription gives you the only the opportunity to follow up or stop following up information on some course), regarding course choosing you should write up one more user story like this: **As a student I want to see all courses on the same page so I can choose what to learn and compare courses quickly.**
2. OK
3. Not detailed enough. I would prefer something like 'As a student I want to participate in assessments related to certain course so I can measure my progress
4. OK
5. OK. Nota bene: this is a great potential feature, but the implementation may require lots of effort
6. OK
7. OK
8. OK
9. Please split up in several stories related to different course content (e.g. presentations, tasks, lections as TXT/MD files), right now it's too general. 
10. OK
11. OK
12. There is an inconsistency in the user story - closing the course means closing it once and forever (at least for me). Either define what does 'close the course' mean or 'close' only the assessment part of the course

**Comment by vasyaxparfenov** [comment]
Fixed version
[backlog.xlsx](https://github.com/PavelLev/CourseManagementSystem/files/509011/backlog.xlsx)

**Comment by zfrgt** [comment]
Great, thanks. I attached the [backlog_prioritized.xlsx](https://github.com/PavelLev/CourseManagementSystem/files/510085/backlog_prioritized.xlsx) with priorities. To sum up the things quickly:
- P1 aka 'musthave': 
  - **Student**: login/logout, view all courses, un\subscribe, view course contents, assess course knowledge level
  - **Lecturer**: login/logout, view assessment results, create courses, add content to them
- P2 aka 'nice-to-have':
  - email notification
- P3 aka 'if time allows':
  - course closing, chat subsystem
